# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: facerec.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfacerec.proto\"\x18\n\x07Payload\x12\r\n\x05image\x18\x01 \x01(\x0c\"\xc7\x01\n\x08Response\x12\'\n\ndetections\x18\x01 \x03(\x0b\x32\x13.Response.Detection\x1a\x42\n\x08Location\x12\x0c\n\x04xmin\x18\x01 \x01(\r\x12\x0c\n\x04ymin\x18\x02 \x01(\r\x12\x0c\n\x04xmax\x18\x03 \x01(\r\x12\x0c\n\x04ymax\x18\x04 \x01(\r\x1aN\n\tDetection\x12$\n\x08location\x18\x01 \x01(\x0b\x32\x12.Response.Location\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05known\x18\x03 \x01(\x08\x32/\n\x0f\x46\x61\x63\x65Recognition\x12\x1c\n\x03run\x12\x08.Payload\x1a\t.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'facerec_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PAYLOAD']._serialized_start=17
  _globals['_PAYLOAD']._serialized_end=41
  _globals['_RESPONSE']._serialized_start=44
  _globals['_RESPONSE']._serialized_end=243
  _globals['_RESPONSE_LOCATION']._serialized_start=97
  _globals['_RESPONSE_LOCATION']._serialized_end=163
  _globals['_RESPONSE_DETECTION']._serialized_start=165
  _globals['_RESPONSE_DETECTION']._serialized_end=243
  _globals['_FACERECOGNITION']._serialized_start=245
  _globals['_FACERECOGNITION']._serialized_end=292
# @@protoc_insertion_point(module_scope)
